name: CommandBlockFinder
main: io.github.meeples10.commandblockfinder.Main
version: %PROJECT_VERSION%
author: Meeples10
description: %PROJECT_DESCRIPTION%
api-version: 1.19
depend: [MeepCore]
commands:
  cbf:
    description: Show the plugin's help message.
    usage: /cbf
    permission: commandblockfinder.use
permissions:
  commandblockfinder.use:
    description: Allows players to use the plugin.
    default: op
